const routes = {
  home: "/",
  aboutUs: "/tong-quan-ve-cong-ty",
  infoCompany: "/thong-tin-cong-ty",
  contact: "/contact",
  expressDelivery: "/chuyen-phat-nhanh",
  economyShipping: "/thue-kho-fulfillment-logistics",
  companyProfile: "/ho-so-cong-ty",
  registerPartner: "doi-tac",
  customerCare: "/lien-he",
  promotions: "/khuyen-mai",
  turtorial: "/huong-dan",
  activity: "/hoat-dong",
  login: "/dang-nhap",
  register: "/dang-ky",
  trackingBill: "/tra-cuu-don-hang",
  career: "/tuyen-dung",
  promoDetails: "/chi-tiet-khuyen-mai",
  actiDetails: "/chi-tiet-hoat-dong",
  tutoDetails: "/chi-tiet-huong-dan",
  serviceDetail: "/dich-vu",
  estimateTariff: "/tinh-phi-van-chuyen",
  privacy: "/chinh-sach-bao-mat",
  support: "/tro-giup",
  privacy: "/chinh-sach",
  rule: "/quy-dinh-chung",
  complain: "/khieu-nai",
  postSystem: "/diem-gui-hang",
  notFound: "*",
};

export default routes;
